const { getOne, runQuery } = require('../config/database');

// UN M49 standard country list (ISO2, ISO3, short_name, official_name, UN_country_code, UNDP_country_code)
const COUNTRIES = [
  ['AF','AFG','Afghanistan','the Islamic Republic of Afghanistan',4,'AFG'],
  ['AL','ALB','Albania','the Republic of Albania',8,'ALB'],
  ['DZ','DZA','Algeria','the People\'s Democratic Republic of Algeria',12,'DZA'],
  ['AD','AND','Andorra','the Principality of Andorra',20,'AND'],
  ['AO','AGO','Angola','the Republic of Angola',24,'AGO'],
  ['AG','ATG','Antigua and Barbuda','Antigua and Barbuda',28,'ATG'],
  ['AR','ARG','Argentina','the Argentine Republic',32,'ARG'],
  ['AM','ARM','Armenia','the Republic of Armenia',51,'ARM'],
  ['AU','AUS','Australia','Australia',36,'AUS'],
  ['AT','AUT','Austria','the Republic of Austria',40,'AUT'],
  ['AZ','AZE','Azerbaijan','the Republic of Azerbaijan',31,'AZE'],
  ['BS','BHS','Bahamas','the Commonwealth of the Bahamas',44,'BHS'],
  ['BH','BHR','Bahrain','the Kingdom of Bahrain',48,'BHR'],
  ['BD','BGD','Bangladesh','the People\'s Republic of Bangladesh',50,'BGD'],
  ['BB','BRB','Barbados','Barbados',52,'BRB'],
  ['BY','BLR','Belarus','the Republic of Belarus',112,'BLR'],
  ['BE','BEL','Belgium','the Kingdom of Belgium',56,'BEL'],
  ['BZ','BLZ','Belize','Belize',84,'BLZ'],
  ['BJ','BEN','Benin','the Republic of Benin',204,'BEN'],
  ['BT','BTN','Bhutan','the Kingdom of Bhutan',64,'BTN'],
  ['BO','BOL','Bolivia (Plurinational State of)','the Plurinational State of Bolivia',68,'BOL'],
  ['BA','BIH','Bosnia and Herzegovina','Bosnia and Herzegovina',70,'BIH'],
  ['BW','BWA','Botswana','the Republic of Botswana',72,'BWA'],
  ['BR','BRA','Brazil','the Federative Republic of Brazil',76,'BRA'],
  ['BN','BRN','Brunei Darussalam','Brunei Darussalam',96,'BRN'],
  ['BG','BGR','Bulgaria','the Republic of Bulgaria',100,'BGR'],
  ['BF','BFA','Burkina Faso','Burkina Faso',854,'BFA'],
  ['BI','BDI','Burundi','the Republic of Burundi',108,'BDI'],
  ['CV','CPV','Cabo Verde','the Republic of Cabo Verde',132,'CPV'],
  ['KH','KHM','Cambodia','the Kingdom of Cambodia',116,'KHM'],
  ['CM','CMR','Cameroon','the Republic of Cameroon',120,'CMR'],
  ['CA','CAN','Canada','Canada',124,'CAN'],
  ['CF','CAF','Central African Republic','the Central African Republic',140,'CAF'],
  ['TD','TCD','Chad','the Republic of Chad',148,'TCD'],
  ['CL','CHL','Chile','the Republic of Chile',152,'CHL'],
  ['CN','CHN','China','the People\'s Republic of China',156,'CHN'],
  ['CO','COL','Colombia','the Republic of Colombia',170,'COL'],
  ['KM','COM','Comoros','the Union of the Comoros',174,'COM'],
  ['CG','COG','Congo','the Republic of the Congo',178,'COG'],
  ['CD','COD','Congo, Democratic Republic of the','the Democratic Republic of the Congo',180,'COD'],
  ['CR','CRI','Costa Rica','the Republic of Costa Rica',188,'CRI'],
  ['CI','CIV','Côte d\'Ivoire','the Republic of Côte d\'Ivoire',384,'CIV'],
  ['HR','HRV','Croatia','the Republic of Croatia',191,'HRV'],
  ['CU','CUB','Cuba','the Republic of Cuba',192,'CUB'],
  ['CY','CYP','Cyprus','the Republic of Cyprus',196,'CYP'],
  ['CZ','CZE','Czechia','the Czech Republic',203,'CZE'],
  ['DK','DNK','Denmark','the Kingdom of Denmark',208,'DNK'],
  ['DJ','DJI','Djibouti','the Republic of Djibouti',262,'DJI'],
  ['DM','DMA','Dominica','the Commonwealth of Dominica',212,'DMA'],
  ['DO','DOM','Dominican Republic','the Dominican Republic',214,'DOM'],
  ['EC','ECU','Ecuador','the Republic of Ecuador',218,'ECU'],
  ['EG','EGY','Egypt','the Arab Republic of Egypt',818,'EGY'],
  ['SV','SLV','El Salvador','the Republic of El Salvador',222,'SLV'],
  ['GQ','GNQ','Equatorial Guinea','the Republic of Equatorial Guinea',226,'GNQ'],
  ['ER','ERI','Eritrea','the State of Eritrea',232,'ERI'],
  ['EE','EST','Estonia','the Republic of Estonia',233,'EST'],
  ['SZ','SWZ','Eswatini','the Kingdom of Eswatini',748,'SWZ'],
  ['ET','ETH','Ethiopia','the Federal Democratic Republic of Ethiopia',231,'ETH'],
  ['FJ','FJI','Fiji','the Republic of Fiji',242,'FJI'],
  ['FI','FIN','Finland','the Republic of Finland',246,'FIN'],
  ['FR','FRA','France','the French Republic',250,'FRA'],
  ['GA','GAB','Gabon','the Gabonese Republic',266,'GAB'],
  ['GM','GMB','Gambia','the Republic of the Gambia',270,'GMB'],
  ['GE','GEO','Georgia','Georgia',268,'GEO'],
  ['DE','DEU','Germany','the Federal Republic of Germany',276,'DEU'],
  ['GH','GHA','Ghana','the Republic of Ghana',288,'GHA'],
  ['GR','GRC','Greece','the Hellenic Republic',300,'GRC'],
  ['GD','GRD','Grenada','Grenada',308,'GRD'],
  ['GT','GTM','Guatemala','the Republic of Guatemala',320,'GTM'],
  ['GN','GIN','Guinea','the Republic of Guinea',324,'GIN'],
  ['GW','GNB','Guinea-Bissau','the Republic of Guinea-Bissau',624,'GNB'],
  ['GY','GUY','Guyana','the Co-operative Republic of Guyana',328,'GUY'],
  ['HT','HTI','Haiti','the Republic of Haiti',332,'HTI'],
  ['HN','HND','Honduras','the Republic of Honduras',340,'HND'],
  ['HU','HUN','Hungary','Hungary',348,'HUN'],
  ['IS','ISL','Iceland','Iceland',352,'ISL'],
  ['IN','IND','India','the Republic of India',356,'IND'],
  ['ID','IDN','Indonesia','the Republic of Indonesia',360,'IDN'],
  ['IR','IRN','Iran (Islamic Republic of)','the Islamic Republic of Iran',364,'IRN'],
  ['IQ','IRQ','Iraq','the Republic of Iraq',368,'IRQ'],
  ['IE','IRL','Ireland','Ireland',372,'IRL'],
  ['IL','ISR','Israel','the State of Israel',376,'ISR'],
  ['IT','ITA','Italy','the Italian Republic',380,'ITA'],
  ['JM','JAM','Jamaica','Jamaica',388,'JAM'],
  ['JP','JPN','Japan','Japan',392,'JPN'],
  ['JO','JOR','Jordan','the Hashemite Kingdom of Jordan',400,'JOR'],
  ['KZ','KAZ','Kazakhstan','the Republic of Kazakhstan',398,'KAZ'],
  ['KE','KEN','Kenya','the Republic of Kenya',404,'KEN'],
  ['KI','KIR','Kiribati','the Republic of Kiribati',296,'KIR'],
  ['KP','PRK','Korea (Democratic People\'s Republic of)','the Democratic People\'s Republic of Korea',408,'PRK'],
  ['KR','KOR','Korea, Republic of','the Republic of Korea',410,'KOR'],
  ['KW','KWT','Kuwait','the State of Kuwait',414,'KWT'],
  ['KG','KGZ','Kyrgyzstan','the Kyrgyz Republic',417,'KGZ'],
  ['LA','LAO','Lao People\'s Democratic Republic','the Lao People\'s Democratic Republic',418,'LAO'],
  ['LV','LVA','Latvia','the Republic of Latvia',428,'LVA'],
  ['LB','LBN','Lebanon','the Lebanese Republic',422,'LBN'],
  ['LS','LSO','Lesotho','the Kingdom of Lesotho',426,'LSO'],
  ['LR','LBR','Liberia','the Republic of Liberia',430,'LBR'],
  ['LY','LBY','Libya','the State of Libya',434,'LBY'],
  ['LI','LIE','Liechtenstein','the Principality of Liechtenstein',438,'LIE'],
  ['LT','LTU','Lithuania','the Republic of Lithuania',440,'LTU'],
  ['LU','LUX','Luxembourg','the Grand Duchy of Luxembourg',442,'LUX'],
  ['MG','MDG','Madagascar','the Republic of Madagascar',450,'MDG'],
  ['MW','MWI','Malawi','the Republic of Malawi',454,'MWI'],
  ['MY','MYS','Malaysia','Malaysia',458,'MYS'],
  ['MV','MDV','Maldives','the Republic of Maldives',462,'MDV'],
  ['ML','MLI','Mali','the Republic of Mali',466,'MLI'],
  ['MT','MLT','Malta','the Republic of Malta',470,'MLT'],
  ['MH','MHL','Marshall Islands','the Republic of the Marshall Islands',584,'MHL'],
  ['MR','MRT','Mauritania','the Islamic Republic of Mauritania',478,'MRT'],
  ['MU','MUS','Mauritius','the Republic of Mauritius',480,'MUS'],
  ['MX','MEX','Mexico','the United Mexican States',484,'MEX'],
  ['FM','FSM','Micronesia (Federated States of)','the Federated States of Micronesia',583,'FSM'],
  ['MD','MDA','Moldova, Republic of','the Republic of Moldova',498,'MDA'],
  ['MC','MCO','Monaco','the Principality of Monaco',492,'MCO'],
  ['MN','MNG','Mongolia','Mongolia',496,'MNG'],
  ['ME','MNE','Montenegro','Montenegro',499,'MNE'],
  ['MA','MAR','Morocco','the Kingdom of Morocco',504,'MAR'],
  ['MZ','MOZ','Mozambique','the Republic of Mozambique',508,'MOZ'],
  ['MM','MMR','Myanmar','the Republic of the Union of Myanmar',104,'MMR'],
  ['NA','NAM','Namibia','the Republic of Namibia',516,'NAM'],
  ['NR','NRU','Nauru','the Republic of Nauru',520,'NRU'],
  ['NP','NPL','Nepal','the Federal Democratic Republic of Nepal',524,'NPL'],
  ['NL','NLD','Netherlands','the Kingdom of the Netherlands',528,'NLD'],
  ['NZ','NZL','New Zealand','New Zealand',554,'NZL'],
  ['NI','NIC','Nicaragua','the Republic of Nicaragua',558,'NIC'],
  ['NE','NER','Niger','the Republic of the Niger',562,'NER'],
  ['NG','NGA','Nigeria','the Federal Republic of Nigeria',566,'NGA'],
  ['MK','MKD','North Macedonia','the Republic of North Macedonia',807,'MKD'],
  ['NO','NOR','Norway','the Kingdom of Norway',578,'NOR'],
  ['OM','OMN','Oman','the Sultanate of Oman',512,'OMN'],
  ['PK','PAK','Pakistan','the Islamic Republic of Pakistan',586,'PAK'],
  ['PW','PLW','Palau','the Republic of Palau',585,'PLW'],
  ['PA','PAN','Panama','the Republic of Panama',591,'PAN'],
  ['PG','PNG','Papua New Guinea','Papua New Guinea',598,'PNG'],
  ['PY','PRY','Paraguay','the Republic of Paraguay',600,'PRY'],
  ['PE','PER','Peru','the Republic of Peru',604,'PER'],
  ['PH','PHL','Philippines','the Republic of the Philippines',608,'PHL'],
  ['PL','POL','Poland','the Republic of Poland',616,'POL'],
  ['PT','PRT','Portugal','the Portuguese Republic',620,'PRT'],
  ['QA','QAT','Qatar','the State of Qatar',634,'QAT'],
  ['RO','ROU','Romania','Romania',642,'ROU'],
  ['RU','RUS','Russian Federation','the Russian Federation',643,'RUS'],
  ['RW','RWA','Rwanda','the Republic of Rwanda',646,'RWA'],
  ['KN','KNA','Saint Kitts and Nevis','Saint Kitts and Nevis',659,'KNA'],
  ['LC','LCA','Saint Lucia','Saint Lucia',662,'LCA'],
  ['VC','VCT','Saint Vincent and the Grenadines','Saint Vincent and the Grenadines',670,'VCT'],
  ['WS','WSM','Samoa','the Independent State of Samoa',882,'WSM'],
  ['SM','SMR','San Marino','the Republic of San Marino',674,'SMR'],
  ['ST','STP','Sao Tome and Principe','the Democratic Republic of Sao Tome and Principe',678,'STP'],
  ['SA','SAU','Saudi Arabia','the Kingdom of Saudi Arabia',682,'SAU'],
  ['SN','SEN','Senegal','the Republic of Senegal',686,'SEN'],
  ['RS','SRB','Serbia','the Republic of Serbia',688,'SRB'],
  ['SC','SYC','Seychelles','the Republic of Seychelles',690,'SYC'],
  ['SL','SLE','Sierra Leone','the Republic of Sierra Leone',694,'SLE'],
  ['SG','SGP','Singapore','the Republic of Singapore',702,'SGP'],
  ['SK','SVK','Slovakia','the Slovak Republic',703,'SVK'],
  ['SI','SVN','Slovenia','the Republic of Slovenia',705,'SVN'],
  ['SB','SLB','Solomon Islands','Solomon Islands',90,'SLB'],
  ['SO','SOM','Somalia','the Federal Republic of Somalia',706,'SOM'],
  ['ZA','ZAF','South Africa','the Republic of South Africa',710,'ZAF'],
  ['SS','SSD','South Sudan','the Republic of South Sudan',728,'SSD'],
  ['ES','ESP','Spain','the Kingdom of Spain',724,'ESP'],
  ['LK','LKA','Sri Lanka','the Democratic Socialist Republic of Sri Lanka',144,'LKA'],
  ['SD','SDN','Sudan','the Republic of the Sudan',729,'SDN'],
  ['SR','SUR','Suriname','the Republic of Suriname',740,'SUR'],
  ['SE','SWE','Sweden','the Kingdom of Sweden',752,'SWE'],
  ['CH','CHE','Switzerland','the Swiss Confederation',756,'CHE'],
  ['SY','SYR','Syrian Arab Republic','the Syrian Arab Republic',760,'SYR'],
  ['TW','TWN','Taiwan, Province of China','Taiwan, Province of China',158,null],
  ['TJ','TJK','Tajikistan','the Republic of Tajikistan',762,'TJK'],
  ['TZ','TZA','Tanzania, United Republic of','the United Republic of Tanzania',834,'TZA'],
  ['TH','THA','Thailand','the Kingdom of Thailand',764,'THA'],
  ['TL','TLS','Timor-Leste','the Democratic Republic of Timor-Leste',626,'TLS'],
  ['TG','TGO','Togo','the Togolese Republic',768,'TGO'],
  ['TO','TON','Tonga','the Kingdom of Tonga',776,'TON'],
  ['TT','TTO','Trinidad and Tobago','the Republic of Trinidad and Tobago',780,'TTO'],
  ['TN','TUN','Tunisia','the Republic of Tunisia',788,'TUN'],
  ['TR','TUR','Türkiye','the Republic of Türkiye',792,'TUR'],
  ['TM','TKM','Turkmenistan','Turkmenistan',795,'TKM'],
  ['TV','TUV','Tuvalu','Tuvalu',798,'TUV'],
  ['UG','UGA','Uganda','the Republic of Uganda',800,'UGA'],
  ['UA','UKR','Ukraine','Ukraine',804,'UKR'],
  ['AE','ARE','United Arab Emirates','the United Arab Emirates',784,'ARE'],
  ['GB','GBR','United Kingdom of Great Britain and Northern Ireland','the United Kingdom of Great Britain and Northern Ireland',826,'GBR'],
  ['US','USA','United States of America','the United States of America',840,'USA'],
  ['UY','URY','Uruguay','the Eastern Republic of Uruguay',858,'URY'],
  ['UZ','UZB','Uzbekistan','the Republic of Uzbekistan',860,'UZB'],
  ['VU','VUT','Vanuatu','the Republic of Vanuatu',548,'VUT'],
  ['VE','VEN','Venezuela (Bolivarian Republic of)','the Bolivarian Republic of Venezuela',862,'VEN'],
  ['VN','VNM','Viet Nam','the Socialist Republic of Viet Nam',704,'VNM'],
  ['YE','YEM','Yemen','the Republic of Yemen',887,'YEM'],
  ['ZM','ZMB','Zambia','the Republic of Zambia',894,'ZMB'],
  ['ZW','ZWE','Zimbabwe','the Republic of Zimbabwe',716,'ZWE'],
  ['PS','PSE','Palestine, State of','the State of Palestine',275,'PSE'],
  ['XK','XKX','Kosovo','the Republic of Kosovo',999,null],
];

async function seedCountries(db) {
  const existing = await getOne(db, 'SELECT COUNT(*) as count FROM countries');
  if (existing.count > 0) {
    console.log('  Countries already seeded, skipping.');
    return;
  }

  console.log(`  Seeding ${COUNTRIES.length} countries...`);
  for (const [iso2, iso3, short_name, official_name, un_code, undp_code] of COUNTRIES) {
    await runQuery(db,
      'INSERT OR IGNORE INTO countries (ISO2, ISO3, short_name, official_name, UN_country_code, UNDP_country_code) VALUES (?, ?, ?, ?, ?, ?)',
      [iso2, iso3, short_name, official_name, un_code, undp_code]
    );
  }
  console.log('  Countries seeded.');
}

module.exports = { seedCountries };
